[package]
name = "ipc"
version = "0.1.0"
edition = "2024"

[features]
default = ["clone-handler"]
clone-handler = []
rwlock-handler = []
sync-handler = []

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }

thiserror = { workspace = true }

logger = { workspace = true }
