[package]
name = "ipc"
version = "0.1.0"
edition = "2021"

[features]
default = ["clone-handler"]
clone-handler = []
rwlock-handler = []
sync-handler = []

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
bincode = "1.3.3"

logger = { version = "0.1.0", path = "../logger" }
